/*const meals = {
	breakfast: [
		"oatmeal",
		"protein pancake",
		"shake",
		"scrambled eggs",
		"fried eggs",
		"omlette",
		"rice porridge",
		"milk rice",
		"sandwich",
		"oat bar",
		"fruit",
		"dessert",
	],
	lunch: [
		"steak",
		"pizza",
		"spaghetti",
		"mac and cheese",
		"chili beans",
		"catfish",
		"rice and meat",
		"lens with meatloaf",
		"salmon",
		"chicken with rice",
		"tuna salad",
		"chicken leg",
	],
	dinner: ["cottage cheese", "eggs", "ham with vegetables", "protein shake", "humus"],
};*/

const meals = [
	// breakfast
	{
		type: "breakfast",
		id: 1,
		name: "oatmeal",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Foatmeal.jpg?alt=media&token=8fa6cf88-8688-4acb-a854-2803563a3c7f",
	},
	{
		type: "breakfast",
		id: 2,
		name: "protein pancake",
		url: "",
	},
	{
		type: "breakfast",
		id: 3,
		name: "shake",
		url: "",
	},
	{
		type: "breakfast",
		id: 4,
		name: "scrambled eggs",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Fscrambled%20eggs.jpg?alt=media&token=35b1714c-480d-40b7-a73d-556fcac2b2bf",
	},
	{
		type: "breakfast",
		id: 5,
		name: "fried eggs",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Ffried%20eggs.jpg?alt=media&token=dcfa9189-f66e-4775-affa-035ad0eb1fd5",
	},
	{
		type: "breakfast",
		id: 6,
		name: "omlette",
		url: "",
	},
	{
		type: "breakfast",
		id: 7,
		name: "rice porridge",
		url: "",
	},
	{
		type: "breakfast",
		id: 8,
		name: "milk rice",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Fmilk%20rice.jpg?alt=media&token=dbd534bb-d852-42f2-9cf6-fad5af47c027",
	},
	{
		type: "breakfast",
		id: 9,
		name: "sandwich",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Fsandwich.jpg?alt=media&token=c7443ec9-8770-402b-ba99-6a8bc314fa7f",
	},
	{
		type: "breakfast",
		id: 10,
		name: "oat bar",
		url: "",
	},
	{
		type: "breakfast",
		id: 11,
		name: "fruit",
		url: "",
	},
	{
		type: "breakfast",
		id: 12,
		name: "bar",
		url: "",
	},
	// lunch
	{
		type: "lunch",
		id: 1,
		name: "steak",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Fsteak.jpg?alt=media&token=6ae60c94-f8e7-4d1c-b0ff-82347d7b6363",
	},
	{
		type: "lunch",
		id: 2,
		name: "pizza",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Fpizza.jpg?alt=media&token=9cf2f948-0c22-495b-8847-81d45b326f1c",
	},
	{
		type: "lunch",
		id: 3,
		name: "spaghetti",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Fspaghetti.jpg?alt=media&token=0f14f4db-f08d-4f58-8143-2eb7e437505a",
	},
	{
		type: "lunch",
		id: 4,
		name: "mac and cheese",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Fmac%20and%20cheese.jpg?alt=media&token=45ac5dd0-17da-4155-83fe-cb93664b2909",
	},
	{
		type: "lunch",
		id: 5,
		name: "chili beans",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Fchili%20beans.jpg?alt=media&token=49abfab8-3d35-4b45-8f97-549cb5b073f2",
	},
	{
		type: "lunch",
		id: 6,
		name: "catfish",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Fcatfish.jpg?alt=media&token=afd55853-94b8-41d2-ae56-f6fa18098c9e",
	},
	{
		type: "lunch",
		id: 7,
		name: "rice and meat",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Frice%20and%20meat.jpg?alt=media&token=5ed5028f-81ff-40cb-8755-19923a34874a",
	},
	{
		type: "lunch",
		id: 8,
		name: "lens with meatloaf",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Flens%20with%20meatloaf.jpg?alt=media&token=4fc8a57a-9c02-4435-a467-4406af61d704",
	},
	{
		type: "lunch",
		id: 9,
		name: "salmon",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Fsalmon.jpg?alt=media&token=3943d24e-b3ee-46a4-9955-effa74506627",
	},
	{
		type: "lunch",
		id: 10,
		name: "chicken with rice",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Fchicken%20with%20rice%202.jpg?alt=media&token=905b8768-8ebb-4e3d-bbde-167992ca895e",
	},
	{
		type: "lunch",
		id: 11,
		name: "tuna salad",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Ftuna%20salad.jpg?alt=media&token=fb669cc0-1467-4b91-a383-854d7601b695",
	},
	{
		type: "lunch",
		id: 12,
		name: "chicken leg",
		url: "https://firebasestorage.googleapis.com/v0/b/thedevilstrainer-e0a02.appspot.com/o/images%2Fmeals%2Fchicken%20leg.jpg?alt=media&token=2ef724c4-ff4f-4722-a169-1591b22c6e36",
	},
	// dinner
	{
		type: "dinner",
		id: 1,
		name: "cottage cheese",
		url: "",
	},
	{
		type: "dinner",
		id: 2,
		name: "eggs",
		url: "",
	},
	{
		type: "dinner",
		id: 3,
		name: "ham with vegetables",
		url: "",
	},
	{
		type: "dinner",
		id: 4,
		name: "protein shake",
		url: "",
	},
	{
		type: "dinner",
		id: 5,
		name: "humus",
		url: "",
	},
];

// Gain muscle
const planBuildMuscleExpensive = [
	// 1. week
	{
		breakfast: [1, 3],
		meal1: [1],
		meal2: [1],
		meal3: [1],
		meal4: [9],
		dinner: [1],
	},
	{
		breakfast: [2, 3],
		meal1: [1],
		meal2: [1],
		meal3: [1],
		meal4: [9],
		dinner: [2],
	},
	{
		breakfast: [3, 4],
		meal1: [1],
		meal2: [1],
		meal3: [1],
		meal4: [9],
		dinner: [1],
	},
	{
		breakfast: [3, 9],
		meal1: [2],
		meal2: [2],
		meal3: [2],
		meal4: [6],
		dinner: [3],
	},
	{
		breakfast: [4, 10],
		meal1: [2],
		meal2: [2],
		meal3: [2],
		meal4: [6],
		dinner: [1],
	},
	{
		breakfast: [5, 11],
		meal1: [3],
		meal2: [3],
		meal3: [3],
		meal4: [11],
		dinner: [4],
	},
	{
		breakfast: [6, 12],
		meal1: [3],
		meal2: [3],
		meal3: [3],
		meal4: [11],
		dinner: [1],
	},
	// 2. week
	{
		breakfast: [1, 3],
		meal1: [4],
		meal2: [4],
		meal3: [4],
		meal4: [7],
		dinner: [1],
	},
	{
		breakfast: [2, 3],
		meal1: [4],
		meal2: [4],
		meal3: [4],
		meal4: [7],
		dinner: [2],
	},
	{
		breakfast: [3, 4],
		meal1: [4],
		meal2: [4],
		meal3: [4],
		meal4: [7],
		dinner: [1],
	},
	{
		breakfast: [3, 9],
		meal1: [5],
		meal2: [5],
		meal3: [5],
		meal4: [8],
		dinner: [3],
	},
	{
		breakfast: [4, 10],
		meal1: [5],
		meal2: [5],
		meal3: [5],
		meal4: [8],
		dinner: [1],
	},
	{
		breakfast: [5, 11],
		meal1: [7],
		meal2: [7],
		meal3: [7],
		meal4: [10],
		dinner: [4],
	},
	{
		breakfast: [6, 12],
		meal1: [7],
		meal2: [7],
		meal3: [7],
		meal4: [10],
		dinner: [1],
	},
	// 3. week
	{
		breakfast: [1, 3],
		meal1: [12],
		meal2: [12],
		meal3: [12],
		meal4: [9],
		dinner: [1],
	},
	{
		breakfast: [2, 3],
		meal1: [12],
		meal2: [12],
		meal3: [12],
		meal4: [9],
		dinner: [2],
	},
	{
		breakfast: [3, 4],
		meal1: [12],
		meal2: [12],
		meal3: [12],
		meal4: [9],
		dinner: [1],
	},
	{
		breakfast: [3, 9],
		meal1: [10],
		meal2: [10],
		meal3: [10],
		meal4: [6],
		dinner: [3],
	},
	{
		breakfast: [4, 10],
		meal1: [10],
		meal2: [10],
		meal3: [10],
		meal4: [6],
		dinner: [1],
	},
	{
		breakfast: [5, 11],
		meal1: [1],
		meal2: [1],
		meal3: [1],
		meal4: [11],
		dinner: [4],
	},
	{
		breakfast: [6, 12],
		meal1: [1],
		meal2: [1],
		meal3: [1],
		meal4: [11],
		dinner: [1],
	},
	// 4. week
	{
		breakfast: [1, 3],
		meal1: [5],
		meal2: [5],
		meal3: [5],
		meal4: [7],
		dinner: [1],
	},
	{
		breakfast: [2, 3],
		meal1: [5],
		meal2: [5],
		meal3: [5],
		meal4: [7],
		dinner: [2],
	},
	{
		breakfast: [3, 4],
		meal1: [5],
		meal2: [5],
		meal3: [5],
		meal4: [7],
		dinner: [1],
	},
	{
		breakfast: [3, 9],
		meal1: [10],
		meal2: [10],
		meal3: [10],
		meal4: [8],
		dinner: [3],
	},
	{
		breakfast: [4, 10],
		meal1: [10],
		meal2: [10],
		meal3: [10],
		meal4: [8],
		dinner: [1],
	},
	{
		breakfast: [5, 11],
		meal1: [12],
		meal2: [12],
		meal3: [12],
		meal4: [10],
		dinner: [4],
	},
	{
		breakfast: [6, 12],
		meal1: [12],
		meal2: [12],
		meal3: [12],
		meal4: [10],
		dinner: [1],
	},
];

const planBuildMuscleCheap = [
	// 1. week
	{
		breakfast: [1, 3],
		meal1: [2],
		meal2: [2],
		meal3: [2],
		meal4: [6],
		dinner: [1],
	},
	{
		breakfast: [2, 3],
		meal1: [2],
		meal2: [2],
		meal3: [2],
		meal4: [6],
		dinner: [2],
	},
	{
		breakfast: [3, 4],
		meal1: [2],
		meal2: [2],
		meal3: [2],
		meal4: [6],
		dinner: [1],
	},
	{
		breakfast: [3, 9],
		meal1: [3],
		meal2: [3],
		meal3: [3],
		meal4: [7],
		dinner: [3],
	},
	{
		breakfast: [4, 10],
		meal1: [3],
		meal2: [3],
		meal3: [3],
		meal4: [7],
		dinner: [1],
	},
	{
		breakfast: [5, 11],
		meal1: [4],
		meal2: [4],
		meal3: [4],
		meal4: [10],
		dinner: [4],
	},
	{
		breakfast: [6, 12],
		meal1: [4],
		meal2: [4],
		meal3: [4],
		meal4: [10],
		dinner: [1],
	},
	// 2. week
	{
		breakfast: [1, 3],
		meal1: [5],
		meal2: [5],
		meal3: [5],
		meal4: [8],
		dinner: [1],
	},
	{
		breakfast: [2, 3],
		meal1: [5],
		meal2: [5],
		meal3: [5],
		meal4: [8],
		dinner: [2],
	},
	{
		breakfast: [3, 4],
		meal1: [5],
		meal2: [5],
		meal3: [5],
		meal4: [8],
		dinner: [1],
	},
	{
		breakfast: [3, 9],
		meal1: [7],
		meal2: [7],
		meal3: [7],
		meal4: [12],
		dinner: [3],
	},
	{
		breakfast: [4, 10],
		meal1: [7],
		meal2: [7],
		meal3: [7],
		meal4: [12],
		dinner: [1],
	},
	{
		breakfast: [5, 11],
		meal1: [8],
		meal2: [8],
		meal3: [8],
		meal4: [7],
		dinner: [4],
	},
	{
		breakfast: [6, 12],
		meal1: [8],
		meal2: [8],
		meal3: [8],
		meal4: [7],
		dinner: [1],
	},
	// 3. week
	{
		breakfast: [1, 3],
		meal1: [10],
		meal2: [10],
		meal3: [10],
		meal4: [6],
		dinner: [1],
	},
	{
		breakfast: [2, 3],
		meal1: [10],
		meal2: [10],
		meal3: [10],
		meal4: [6],
		dinner: [2],
	},
	{
		breakfast: [3, 4],
		meal1: [10],
		meal2: [10],
		meal3: [10],
		meal4: [6],
		dinner: [1],
	},
	{
		breakfast: [3, 9],
		meal1: [12],
		meal2: [12],
		meal3: [12],
		meal4: [7],
		dinner: [3],
	},
	{
		breakfast: [4, 10],
		meal1: [12],
		meal2: [12],
		meal3: [12],
		meal4: [7],
		dinner: [1],
	},
	{
		breakfast: [5, 11],
		meal1: [2],
		meal2: [2],
		meal3: [2],
		meal4: [10],
		dinner: [4],
	},
	{
		breakfast: [6, 12],
		meal1: [2],
		meal2: [2],
		meal3: [2],
		meal4: [10],
		dinner: [1],
	},
	// 4. week
	{
		breakfast: [1, 3],
		meal1: [3],
		meal2: [3],
		meal3: [3],
		meal4: [8],
		dinner: [1],
	},
	{
		breakfast: [2, 3],
		meal1: [3],
		meal2: [3],
		meal3: [3],
		meal4: [8],
		dinner: [2],
	},
	{
		breakfast: [3, 4],
		meal1: [3],
		meal2: [3],
		meal3: [3],
		meal4: [8],
		dinner: [1],
	},
	{
		breakfast: [3, 9],
		meal1: [4],
		meal2: [4],
		meal3: [4],
		meal4: [12],
		dinner: [3],
	},
	{
		breakfast: [4, 10],
		meal1: [4],
		meal2: [4],
		meal3: [4],
		meal4: [12],
		dinner: [1],
	},
	{
		breakfast: [5, 11],
		meal1: [5],
		meal2: [5],
		meal3: [5],
		meal4: [7],
		dinner: [4],
	},
	{
		breakfast: [6, 12],
		meal1: [5],
		meal2: [5],
		meal3: [5],
		meal4: [7],
		dinner: [1],
	},
];

// Lose weight
const planLoseWeightExpensive = [
	// 1. week
	{
		breakfast: [1],
		meal1: [7],
		meal2: [7],
		meal3: [9],
		dinner: [2],
	},
	{
		breakfast: [3],
		meal1: [7],
		meal2: [7],
		meal3: [9],
		dinner: [4],
	},
	{
		breakfast: [4],
		meal1: [8],
		meal2: [8],
		meal3: [10],
		dinner: [4],
	},
	{
		breakfast: [5],
		meal1: [8],
		meal2: [8],
		meal3: [9],
		dinner: [3],
	},
	{
		breakfast: [6],
		meal1: [9],
		meal2: [9],
		meal3: [10],
		dinner: [5],
	},
	{
		breakfast: [7],
		meal1: [5],
		meal2: [5],
		meal3: [8],
		dinner: [4],
	},
	{
		breakfast: [8],
		meal1: [1],
		meal2: [1],
		meal3: [8],
		dinner: [1],
	},
	// 2. week
	{
		breakfast: [1],
		meal1: [10],
		meal2: [10],
		meal3: [11],
		dinner: [2],
	},
	{
		breakfast: [3],
		meal1: [10],
		meal2: [10],
		meal3: [11],
		dinner: [4],
	},
	{
		breakfast: [4],
		meal1: [11],
		meal2: [11],
		meal3: [11],
		dinner: [3],
	},
	{
		breakfast: [5],
		meal1: [11],
		meal2: [11],
		meal3: [6],
		dinner: [4],
	},
	{
		breakfast: [6],
		meal1: [12],
		meal2: [12],
		meal3: [6],
		dinner: [5],
	},
	{
		breakfast: [7],
		meal1: [6],
		meal2: [6],
		meal3: [7],
		dinner: [4],
	},
	{
		breakfast: [8],
		meal1: [2],
		meal2: [2],
		meal3: [7],
		dinner: [1],
	},
	// 3. week
	{
		breakfast: [1],
		meal1: [7],
		meal2: [7],
		meal3: [9],
		dinner: [2],
	},
	{
		breakfast: [3],
		meal1: [7],
		meal2: [7],
		meal3: [9],
		dinner: [4],
	},
	{
		breakfast: [4],
		meal1: [8],
		meal2: [8],
		meal3: [9],
		dinner: [3],
	},
	{
		breakfast: [5],
		meal1: [8],
		meal2: [8],
		meal3: [10],
		dinner: [4],
	},
	{
		breakfast: [6],
		meal1: [9],
		meal2: [9],
		meal3: [10],
		dinner: [5],
	},
	{
		breakfast: [7],
		meal1: [5],
		meal2: [5],
		meal3: [8],
		dinner: [4],
	},
	{
		breakfast: [8],
		meal1: [3],
		meal2: [3],
		meal3: [8],
		dinner: [1],
	},
	// 4. week
	{
		breakfast: [1],
		meal1: [10],
		meal2: [10],
		meal3: [11],
		dinner: [2],
	},
	{
		breakfast: [3],
		meal1: [10],
		meal2: [10],
		meal3: [11],
		dinner: [4],
	},
	{
		breakfast: [4],
		meal1: [11],
		meal2: [11],
		meal3: [11],
		dinner: [3],
	},
	{
		breakfast: [5],
		meal1: [11],
		meal2: [11],
		meal3: [6],
		dinner: [4],
	},
	{
		breakfast: [6],
		meal1: [12],
		meal2: [12],
		meal3: [6],
		dinner: [5],
	},
	{
		breakfast: [7],
		meal1: [6],
		meal2: [6],
		meal3: [7],
		dinner: [4],
	},
	{
		breakfast: [8],
		meal1: [4],
		meal2: [4],
		meal3: [7],
		dinner: [1],
	},
];

const planLoseWeightCheap = [
	// 1. week
	{
		breakfast: [1],
		meal1: [7],
		meal2: [7],
		meal3: [6],
		dinner: [2],
	},
	{
		breakfast: [3],
		meal1: [7],
		meal2: [7],
		meal3: [6],
		dinner: [4],
	},
	{
		breakfast: [4],
		meal1: [8],
		meal2: [8],
		meal3: [6],
		dinner: [3],
	},
	{
		breakfast: [5],
		meal1: [8],
		meal2: [8],
		meal3: [7],
		dinner: [4],
	},
	{
		breakfast: [6],
		meal1: [10],
		meal2: [10],
		meal3: [7],
		dinner: [5],
	},
	{
		breakfast: [7],
		meal1: [10],
		meal2: [10],
		meal3: [8],
		dinner: [4],
	},
	{
		breakfast: [8],
		meal1: [2],
		meal2: [2],
		meal3: [8],
		dinner: [1],
	},
	// 2. week
	{
		breakfast: [1],
		meal1: [12],
		meal2: [12],
		meal3: [10],
		dinner: [2],
	},
	{
		breakfast: [3],
		meal1: [12],
		meal2: [12],
		meal3: [10],
		dinner: [4],
	},
	{
		breakfast: [4],
		meal1: [7],
		meal2: [7],
		meal3: [10],
		dinner: [3],
	},
	{
		breakfast: [5],
		meal1: [7],
		meal2: [7],
		meal3: [7],
		dinner: [4],
	},
	{
		breakfast: [6],
		meal1: [8],
		meal2: [8],
		meal3: [5],
		dinner: [5],
	},
	{
		breakfast: [7],
		meal1: [8],
		meal2: [8],
		meal3: [8],
		dinner: [4],
	},
	{
		breakfast: [8],
		meal1: [3],
		meal2: [3],
		meal3: [8],
		dinner: [1],
	},
	// 3. week
	{
		breakfast: [1],
		meal1: [10],
		meal2: [10],
		meal3: [6],
		dinner: [2],
	},
	{
		breakfast: [3],
		meal1: [10],
		meal2: [10],
		meal3: [6],
		dinner: [4],
	},
	{
		breakfast: [4],
		meal1: [12],
		meal2: [12],
		meal3: [6],
		dinner: [3],
	},
	{
		breakfast: [5],
		meal1: [12],
		meal2: [12],
		meal3: [7],
		dinner: [4],
	},
	{
		breakfast: [6],
		meal1: [7],
		meal2: [7],
		meal3: [7],
		dinner: [5],
	},
	{
		breakfast: [7],
		meal1: [7],
		meal2: [7],
		meal3: [8],
		dinner: [4],
	},
	{
		breakfast: [8],
		meal1: [6],
		meal2: [6],
		meal3: [8],
		dinner: [1],
	},
	// 4. week
	{
		breakfast: [1],
		meal1: [8],
		meal2: [8],
		meal3: [10],
		dinner: [2],
	},
	{
		breakfast: [3],
		meal1: [8],
		meal2: [8],
		meal3: [10],
		dinner: [4],
	},
	{
		breakfast: [4],
		meal1: [10],
		meal2: [10],
		meal3: [10],
		dinner: [3],
	},
	{
		breakfast: [5],
		meal1: [10],
		meal2: [10],
		meal3: [7],
		dinner: [4],
	},
	{
		breakfast: [6],
		meal1: [12],
		meal2: [12],
		meal3: [7],
		dinner: [5],
	},
	{
		breakfast: [7],
		meal1: [12],
		meal2: [12],
		meal3: [8],
		dinner: [4],
	},
	{
		breakfast: [8],
		meal1: [5],
		meal2: [5],
		meal3: [8],
		dinner: [1],
	},
];

// Functions to get the daily meal plan based on the parameters
function mealType(goal, food) {
	if (goal === "loseWeight" && food === "less") return planLoseWeightCheap;
	if (goal === "loseWeight" && food === "more") return planLoseWeightExpensive;
	if (goal === "buildMuscle" && food === "less") return planBuildMuscleCheap;
	if (goal === "buildMuscle" && food === "more") return planBuildMuscleExpensive;
}

// Returns the daily meal object
function getMeals(dailyMeal) {
	let obj = {};
	for (let meal in dailyMeal) {
		if (meal === "breakfast" || meal === "dinner")
			obj[meal] = dailyMeal[meal].map((id) => meals.filter((m) => m.type === meal && m.id === id)[0]);
		if (meal === "meal1" || meal === "meal2" || meal === "meal3" || meal === "meal4")
			obj[meal] = dailyMeal[meal].map((id) => meals.filter((m) => m.type === "lunch" && m.id === id)[0]);
	}
	return obj;
}

export { getMeals, mealType };
